### ISSUE TITLE
data problem

### ISSUE THREAD

**Issue by Carina0** [PanosAntoniadis/emotion-gcn#1]
Hello！ Thank you to your reply！ Nowadays， I have a new problem. I couldn't understand the ‘data’ file. Could you explain it for me? And the ‘data_affectnet.pkl’ and ‘spearman_affectnet.pkl’ are so small. Are there any errors？Thanks for your reply！Best wishes！

**Comment by PanosAntoniadis** [comment]
Hello! 

The `/data` folder contains various files regarding data manipulation. More specifically, `data_affectnet.pkl` is a pickle file that contains all the annotations of AffectNet in a proper format.

First, you should run `python pickle_annotations_affectnet.py` as stated in README.md to generate your own data_affectnet.pkl file given that you have downloaded the dataset. The uploaded file is small because it does not correspond to the whole AffectNet dataset.

The file `spearman_affectnet.pkl` contains the spearman correlation matrix used in the GCN and is already ready for use.

In case you still have any problems, please let me know. I will try to update README.md with more details.
